name: Consume Assets from Assets-Repository

on:
  repository_dispatch:
    types: [update-assets]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Download artifact
        #uses: actions/download-artifact@v2
        #with:
        # name: ${{ github.event.client_payload.artifact_name }}
        env:
          ARTIFACT_NAME: ${{ github.event.client_payload.artifact_name }}
        run: |
          curl -sSL \
             -H "Authorization: Bearer ${{ secrets.DOWNLOAD_ACCESS }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/guilhermeqmaia/assets_repository/actions/artifacts \
             | jq -r '.artifacts[] | select(.name == env.ARTIFACT_NAME) | .archive_download_url' \
             | xargs curl -sSL -H "Authorization: Bearer ${{ secrets.DOWNLOAD_ACCESS }}" -o assets.zip


      - name: Extract artifact
        run: |
          unzip -qq ${{ github.event.client_payload.artifact_name }} -d 'assets/images/'
          
      - name: Setup Git Config
        run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git branch ${{ github.event.client_payload.branch_name }}
           git checkout ${{ github.event.client_payload.branch_name }}
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Add files from artifact"
          git push origin ${{ github.event.client_payload.branch_name }}
          
      - name: Create Pull Request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.client_payload.branch_name }}                        
          destination_branch: "main"                      
          pr_title: "Atualização de assets" 
          pr_body: "Esse PR traz novas atualizações de assets"             
          pr_label: "assets/update"                               
          pr_draft: false                                    
          pr_allow_empty: false                           
          github_token: ${{ secrets.CREATE_PR_ACCESS }}
